// Code generated by ent, DO NOT EDIT.

package account

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the account type in the database.
	Label = "account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMnemonic holds the string denoting the mnemonic field in the database.
	FieldMnemonic = "mnemonic"
	// FieldAddress holds the string denoting the address field in the database.
	FieldAddress = "address"
	// FieldPrivateKey holds the string denoting the privatekey field in the database.
	FieldPrivateKey = "private_key"
	// EdgeStepRuns holds the string denoting the step_runs edge name in mutations.
	EdgeStepRuns = "step_runs"
	// Table holds the table name of the account in the database.
	Table = "accounts"
	// StepRunsTable is the table that holds the step_runs relation/edge.
	StepRunsTable = "step_runs"
	// StepRunsInverseTable is the table name for the StepRun entity.
	// It exists in this package in order to avoid circular dependency with the "steprun" package.
	StepRunsInverseTable = "step_runs"
	// StepRunsColumn is the table column denoting the step_runs relation/edge.
	StepRunsColumn = "account_step_runs"
)

// Columns holds all SQL columns for account fields.
var Columns = []string{
	FieldID,
	FieldMnemonic,
	FieldAddress,
	FieldPrivateKey,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Account queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByMnemonic orders the results by the mnemonic field.
func ByMnemonic(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMnemonic, opts...).ToFunc()
}

// ByAddress orders the results by the address field.
func ByAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAddress, opts...).ToFunc()
}

// ByPrivateKey orders the results by the privateKey field.
func ByPrivateKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrivateKey, opts...).ToFunc()
}

// ByStepRunsCount orders the results by step_runs count.
func ByStepRunsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newStepRunsStep(), opts...)
	}
}

// ByStepRuns orders the results by step_runs terms.
func ByStepRuns(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStepRunsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newStepRunsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StepRunsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, StepRunsTable, StepRunsColumn),
	)
}
