// Code generated by ent, DO NOT EDIT.

package account

import (
	"airdrop-bot/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldID, id))
}

// Mnemonic applies equality check predicate on the "mnemonic" field. It's identical to MnemonicEQ.
func Mnemonic(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldMnemonic, v))
}

// Address applies equality check predicate on the "address" field. It's identical to AddressEQ.
func Address(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldAddress, v))
}

// PrivateKey applies equality check predicate on the "privateKey" field. It's identical to PrivateKeyEQ.
func PrivateKey(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldPrivateKey, v))
}

// MnemonicEQ applies the EQ predicate on the "mnemonic" field.
func MnemonicEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldMnemonic, v))
}

// MnemonicNEQ applies the NEQ predicate on the "mnemonic" field.
func MnemonicNEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldMnemonic, v))
}

// MnemonicIn applies the In predicate on the "mnemonic" field.
func MnemonicIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldMnemonic, vs...))
}

// MnemonicNotIn applies the NotIn predicate on the "mnemonic" field.
func MnemonicNotIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldMnemonic, vs...))
}

// MnemonicGT applies the GT predicate on the "mnemonic" field.
func MnemonicGT(v string) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldMnemonic, v))
}

// MnemonicGTE applies the GTE predicate on the "mnemonic" field.
func MnemonicGTE(v string) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldMnemonic, v))
}

// MnemonicLT applies the LT predicate on the "mnemonic" field.
func MnemonicLT(v string) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldMnemonic, v))
}

// MnemonicLTE applies the LTE predicate on the "mnemonic" field.
func MnemonicLTE(v string) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldMnemonic, v))
}

// MnemonicContains applies the Contains predicate on the "mnemonic" field.
func MnemonicContains(v string) predicate.Account {
	return predicate.Account(sql.FieldContains(FieldMnemonic, v))
}

// MnemonicHasPrefix applies the HasPrefix predicate on the "mnemonic" field.
func MnemonicHasPrefix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasPrefix(FieldMnemonic, v))
}

// MnemonicHasSuffix applies the HasSuffix predicate on the "mnemonic" field.
func MnemonicHasSuffix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasSuffix(FieldMnemonic, v))
}

// MnemonicEqualFold applies the EqualFold predicate on the "mnemonic" field.
func MnemonicEqualFold(v string) predicate.Account {
	return predicate.Account(sql.FieldEqualFold(FieldMnemonic, v))
}

// MnemonicContainsFold applies the ContainsFold predicate on the "mnemonic" field.
func MnemonicContainsFold(v string) predicate.Account {
	return predicate.Account(sql.FieldContainsFold(FieldMnemonic, v))
}

// AddressEQ applies the EQ predicate on the "address" field.
func AddressEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldAddress, v))
}

// AddressNEQ applies the NEQ predicate on the "address" field.
func AddressNEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldAddress, v))
}

// AddressIn applies the In predicate on the "address" field.
func AddressIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldAddress, vs...))
}

// AddressNotIn applies the NotIn predicate on the "address" field.
func AddressNotIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldAddress, vs...))
}

// AddressGT applies the GT predicate on the "address" field.
func AddressGT(v string) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldAddress, v))
}

// AddressGTE applies the GTE predicate on the "address" field.
func AddressGTE(v string) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldAddress, v))
}

// AddressLT applies the LT predicate on the "address" field.
func AddressLT(v string) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldAddress, v))
}

// AddressLTE applies the LTE predicate on the "address" field.
func AddressLTE(v string) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldAddress, v))
}

// AddressContains applies the Contains predicate on the "address" field.
func AddressContains(v string) predicate.Account {
	return predicate.Account(sql.FieldContains(FieldAddress, v))
}

// AddressHasPrefix applies the HasPrefix predicate on the "address" field.
func AddressHasPrefix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasPrefix(FieldAddress, v))
}

// AddressHasSuffix applies the HasSuffix predicate on the "address" field.
func AddressHasSuffix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasSuffix(FieldAddress, v))
}

// AddressEqualFold applies the EqualFold predicate on the "address" field.
func AddressEqualFold(v string) predicate.Account {
	return predicate.Account(sql.FieldEqualFold(FieldAddress, v))
}

// AddressContainsFold applies the ContainsFold predicate on the "address" field.
func AddressContainsFold(v string) predicate.Account {
	return predicate.Account(sql.FieldContainsFold(FieldAddress, v))
}

// PrivateKeyEQ applies the EQ predicate on the "privateKey" field.
func PrivateKeyEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldPrivateKey, v))
}

// PrivateKeyNEQ applies the NEQ predicate on the "privateKey" field.
func PrivateKeyNEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldPrivateKey, v))
}

// PrivateKeyIn applies the In predicate on the "privateKey" field.
func PrivateKeyIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldPrivateKey, vs...))
}

// PrivateKeyNotIn applies the NotIn predicate on the "privateKey" field.
func PrivateKeyNotIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldPrivateKey, vs...))
}

// PrivateKeyGT applies the GT predicate on the "privateKey" field.
func PrivateKeyGT(v string) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldPrivateKey, v))
}

// PrivateKeyGTE applies the GTE predicate on the "privateKey" field.
func PrivateKeyGTE(v string) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldPrivateKey, v))
}

// PrivateKeyLT applies the LT predicate on the "privateKey" field.
func PrivateKeyLT(v string) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldPrivateKey, v))
}

// PrivateKeyLTE applies the LTE predicate on the "privateKey" field.
func PrivateKeyLTE(v string) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldPrivateKey, v))
}

// PrivateKeyContains applies the Contains predicate on the "privateKey" field.
func PrivateKeyContains(v string) predicate.Account {
	return predicate.Account(sql.FieldContains(FieldPrivateKey, v))
}

// PrivateKeyHasPrefix applies the HasPrefix predicate on the "privateKey" field.
func PrivateKeyHasPrefix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasPrefix(FieldPrivateKey, v))
}

// PrivateKeyHasSuffix applies the HasSuffix predicate on the "privateKey" field.
func PrivateKeyHasSuffix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasSuffix(FieldPrivateKey, v))
}

// PrivateKeyEqualFold applies the EqualFold predicate on the "privateKey" field.
func PrivateKeyEqualFold(v string) predicate.Account {
	return predicate.Account(sql.FieldEqualFold(FieldPrivateKey, v))
}

// PrivateKeyContainsFold applies the ContainsFold predicate on the "privateKey" field.
func PrivateKeyContainsFold(v string) predicate.Account {
	return predicate.Account(sql.FieldContainsFold(FieldPrivateKey, v))
}

// HasStepRuns applies the HasEdge predicate on the "step_runs" edge.
func HasStepRuns() predicate.Account {
	return predicate.Account(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, StepRunsTable, StepRunsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStepRunsWith applies the HasEdge predicate on the "step_runs" edge with a given conditions (other predicates).
func HasStepRunsWith(preds ...predicate.StepRun) predicate.Account {
	return predicate.Account(func(s *sql.Selector) {
		step := newStepRunsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Account) predicate.Account {
	return predicate.Account(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Account) predicate.Account {
	return predicate.Account(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Account) predicate.Account {
	return predicate.Account(func(s *sql.Selector) {
		p(s.Not())
	})
}
