// Code generated by ent, DO NOT EDIT.

package ent

import (
	"airdrop-bot/ent/account"
	"airdrop-bot/ent/predicate"
	"airdrop-bot/ent/steprun"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AccountUpdate is the builder for updating Account entities.
type AccountUpdate struct {
	config
	hooks    []Hook
	mutation *AccountMutation
}

// Where appends a list predicates to the AccountUpdate builder.
func (au *AccountUpdate) Where(ps ...predicate.Account) *AccountUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetMnemonic sets the "mnemonic" field.
func (au *AccountUpdate) SetMnemonic(s string) *AccountUpdate {
	au.mutation.SetMnemonic(s)
	return au
}

// SetAddress sets the "address" field.
func (au *AccountUpdate) SetAddress(s string) *AccountUpdate {
	au.mutation.SetAddress(s)
	return au
}

// SetPrivateKey sets the "privateKey" field.
func (au *AccountUpdate) SetPrivateKey(s string) *AccountUpdate {
	au.mutation.SetPrivateKey(s)
	return au
}

// AddStepRunIDs adds the "step_runs" edge to the StepRun entity by IDs.
func (au *AccountUpdate) AddStepRunIDs(ids ...int) *AccountUpdate {
	au.mutation.AddStepRunIDs(ids...)
	return au
}

// AddStepRuns adds the "step_runs" edges to the StepRun entity.
func (au *AccountUpdate) AddStepRuns(s ...*StepRun) *AccountUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return au.AddStepRunIDs(ids...)
}

// Mutation returns the AccountMutation object of the builder.
func (au *AccountUpdate) Mutation() *AccountMutation {
	return au.mutation
}

// ClearStepRuns clears all "step_runs" edges to the StepRun entity.
func (au *AccountUpdate) ClearStepRuns() *AccountUpdate {
	au.mutation.ClearStepRuns()
	return au
}

// RemoveStepRunIDs removes the "step_runs" edge to StepRun entities by IDs.
func (au *AccountUpdate) RemoveStepRunIDs(ids ...int) *AccountUpdate {
	au.mutation.RemoveStepRunIDs(ids...)
	return au
}

// RemoveStepRuns removes "step_runs" edges to StepRun entities.
func (au *AccountUpdate) RemoveStepRuns(s ...*StepRun) *AccountUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return au.RemoveStepRunIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AccountUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, AccountMutation](ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *AccountUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AccountUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AccountUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

func (au *AccountUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(account.Table, account.Columns, sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.Mnemonic(); ok {
		_spec.SetField(account.FieldMnemonic, field.TypeString, value)
	}
	if value, ok := au.mutation.Address(); ok {
		_spec.SetField(account.FieldAddress, field.TypeString, value)
	}
	if value, ok := au.mutation.PrivateKey(); ok {
		_spec.SetField(account.FieldPrivateKey, field.TypeString, value)
	}
	if au.mutation.StepRunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.StepRunsTable,
			Columns: []string{account.StepRunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(steprun.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedStepRunsIDs(); len(nodes) > 0 && !au.mutation.StepRunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.StepRunsTable,
			Columns: []string{account.StepRunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(steprun.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.StepRunsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.StepRunsTable,
			Columns: []string{account.StepRunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(steprun.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// AccountUpdateOne is the builder for updating a single Account entity.
type AccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountMutation
}

// SetMnemonic sets the "mnemonic" field.
func (auo *AccountUpdateOne) SetMnemonic(s string) *AccountUpdateOne {
	auo.mutation.SetMnemonic(s)
	return auo
}

// SetAddress sets the "address" field.
func (auo *AccountUpdateOne) SetAddress(s string) *AccountUpdateOne {
	auo.mutation.SetAddress(s)
	return auo
}

// SetPrivateKey sets the "privateKey" field.
func (auo *AccountUpdateOne) SetPrivateKey(s string) *AccountUpdateOne {
	auo.mutation.SetPrivateKey(s)
	return auo
}

// AddStepRunIDs adds the "step_runs" edge to the StepRun entity by IDs.
func (auo *AccountUpdateOne) AddStepRunIDs(ids ...int) *AccountUpdateOne {
	auo.mutation.AddStepRunIDs(ids...)
	return auo
}

// AddStepRuns adds the "step_runs" edges to the StepRun entity.
func (auo *AccountUpdateOne) AddStepRuns(s ...*StepRun) *AccountUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return auo.AddStepRunIDs(ids...)
}

// Mutation returns the AccountMutation object of the builder.
func (auo *AccountUpdateOne) Mutation() *AccountMutation {
	return auo.mutation
}

// ClearStepRuns clears all "step_runs" edges to the StepRun entity.
func (auo *AccountUpdateOne) ClearStepRuns() *AccountUpdateOne {
	auo.mutation.ClearStepRuns()
	return auo
}

// RemoveStepRunIDs removes the "step_runs" edge to StepRun entities by IDs.
func (auo *AccountUpdateOne) RemoveStepRunIDs(ids ...int) *AccountUpdateOne {
	auo.mutation.RemoveStepRunIDs(ids...)
	return auo
}

// RemoveStepRuns removes "step_runs" edges to StepRun entities.
func (auo *AccountUpdateOne) RemoveStepRuns(s ...*StepRun) *AccountUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return auo.RemoveStepRunIDs(ids...)
}

// Where appends a list predicates to the AccountUpdate builder.
func (auo *AccountUpdateOne) Where(ps ...predicate.Account) *AccountUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AccountUpdateOne) Select(field string, fields ...string) *AccountUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Account entity.
func (auo *AccountUpdateOne) Save(ctx context.Context) (*Account, error) {
	return withHooks[*Account, AccountMutation](ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AccountUpdateOne) SaveX(ctx context.Context) *Account {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AccountUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AccountUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (auo *AccountUpdateOne) sqlSave(ctx context.Context) (_node *Account, err error) {
	_spec := sqlgraph.NewUpdateSpec(account.Table, account.Columns, sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Account.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, account.FieldID)
		for _, f := range fields {
			if !account.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != account.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.Mnemonic(); ok {
		_spec.SetField(account.FieldMnemonic, field.TypeString, value)
	}
	if value, ok := auo.mutation.Address(); ok {
		_spec.SetField(account.FieldAddress, field.TypeString, value)
	}
	if value, ok := auo.mutation.PrivateKey(); ok {
		_spec.SetField(account.FieldPrivateKey, field.TypeString, value)
	}
	if auo.mutation.StepRunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.StepRunsTable,
			Columns: []string{account.StepRunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(steprun.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedStepRunsIDs(); len(nodes) > 0 && !auo.mutation.StepRunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.StepRunsTable,
			Columns: []string{account.StepRunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(steprun.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.StepRunsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.StepRunsTable,
			Columns: []string{account.StepRunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(steprun.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Account{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
