// Code generated by entc, DO NOT EDIT.

package ent

import (
	"airdrop-bot/ent/account"
	"airdrop-bot/ent/node"
	"airdrop-bot/ent/predicate"
	"airdrop-bot/ent/steprun"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StepRunUpdate is the builder for updating StepRun entities.
type StepRunUpdate struct {
	config
	hooks    []Hook
	mutation *StepRunMutation
}

// Where appends a list predicates to the StepRunUpdate builder.
func (sru *StepRunUpdate) Where(ps ...predicate.StepRun) *StepRunUpdate {
	sru.mutation.Where(ps...)
	return sru
}

// SetStep sets the "step" field.
func (sru *StepRunUpdate) SetStep(s string) *StepRunUpdate {
	sru.mutation.SetStep(s)
	return sru
}

// SetStatus sets the "status" field.
func (sru *StepRunUpdate) SetStatus(s steprun.Status) *StepRunUpdate {
	sru.mutation.SetStatus(s)
	return sru
}

// SetReason sets the "reason" field.
func (sru *StepRunUpdate) SetReason(s string) *StepRunUpdate {
	sru.mutation.SetReason(s)
	return sru
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (sru *StepRunUpdate) SetAccountID(id int) *StepRunUpdate {
	sru.mutation.SetAccountID(id)
	return sru
}

// SetNillableAccountID sets the "account" edge to the Account entity by ID if the given value is not nil.
func (sru *StepRunUpdate) SetNillableAccountID(id *int) *StepRunUpdate {
	if id != nil {
		sru = sru.SetAccountID(*id)
	}
	return sru
}

// SetAccount sets the "account" edge to the Account entity.
func (sru *StepRunUpdate) SetAccount(a *Account) *StepRunUpdate {
	return sru.SetAccountID(a.ID)
}

// SetNodeID sets the "node" edge to the Node entity by ID.
func (sru *StepRunUpdate) SetNodeID(id int) *StepRunUpdate {
	sru.mutation.SetNodeID(id)
	return sru
}

// SetNillableNodeID sets the "node" edge to the Node entity by ID if the given value is not nil.
func (sru *StepRunUpdate) SetNillableNodeID(id *int) *StepRunUpdate {
	if id != nil {
		sru = sru.SetNodeID(*id)
	}
	return sru
}

// SetNode sets the "node" edge to the Node entity.
func (sru *StepRunUpdate) SetNode(n *Node) *StepRunUpdate {
	return sru.SetNodeID(n.ID)
}

// Mutation returns the StepRunMutation object of the builder.
func (sru *StepRunUpdate) Mutation() *StepRunMutation {
	return sru.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (sru *StepRunUpdate) ClearAccount() *StepRunUpdate {
	sru.mutation.ClearAccount()
	return sru
}

// ClearNode clears the "node" edge to the Node entity.
func (sru *StepRunUpdate) ClearNode() *StepRunUpdate {
	sru.mutation.ClearNode()
	return sru
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (sru *StepRunUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(sru.hooks) == 0 {
		if err = sru.check(); err != nil {
			return 0, err
		}
		affected, err = sru.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*StepRunMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = sru.check(); err != nil {
				return 0, err
			}
			sru.mutation = mutation
			affected, err = sru.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(sru.hooks) - 1; i >= 0; i-- {
			if sru.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = sru.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sru.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (sru *StepRunUpdate) SaveX(ctx context.Context) int {
	affected, err := sru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (sru *StepRunUpdate) Exec(ctx context.Context) error {
	_, err := sru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sru *StepRunUpdate) ExecX(ctx context.Context) {
	if err := sru.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sru *StepRunUpdate) check() error {
	if v, ok := sru.mutation.Status(); ok {
		if err := steprun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "StepRun.status": %w`, err)}
		}
	}
	return nil
}

func (sru *StepRunUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   steprun.Table,
			Columns: steprun.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: steprun.FieldID,
			},
		},
	}
	if ps := sru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := sru.mutation.Step(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: steprun.FieldStep,
		})
	}
	if value, ok := sru.mutation.Status(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: steprun.FieldStatus,
		})
	}
	if value, ok := sru.mutation.Reason(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: steprun.FieldReason,
		})
	}
	if sru.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   steprun.AccountTable,
			Columns: []string{steprun.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: account.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := sru.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   steprun.AccountTable,
			Columns: []string{steprun.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: account.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if sru.mutation.NodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   steprun.NodeTable,
			Columns: []string{steprun.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: node.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := sru.mutation.NodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   steprun.NodeTable,
			Columns: []string{steprun.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: node.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, sru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{steprun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// StepRunUpdateOne is the builder for updating a single StepRun entity.
type StepRunUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StepRunMutation
}

// SetStep sets the "step" field.
func (sruo *StepRunUpdateOne) SetStep(s string) *StepRunUpdateOne {
	sruo.mutation.SetStep(s)
	return sruo
}

// SetStatus sets the "status" field.
func (sruo *StepRunUpdateOne) SetStatus(s steprun.Status) *StepRunUpdateOne {
	sruo.mutation.SetStatus(s)
	return sruo
}

// SetReason sets the "reason" field.
func (sruo *StepRunUpdateOne) SetReason(s string) *StepRunUpdateOne {
	sruo.mutation.SetReason(s)
	return sruo
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (sruo *StepRunUpdateOne) SetAccountID(id int) *StepRunUpdateOne {
	sruo.mutation.SetAccountID(id)
	return sruo
}

// SetNillableAccountID sets the "account" edge to the Account entity by ID if the given value is not nil.
func (sruo *StepRunUpdateOne) SetNillableAccountID(id *int) *StepRunUpdateOne {
	if id != nil {
		sruo = sruo.SetAccountID(*id)
	}
	return sruo
}

// SetAccount sets the "account" edge to the Account entity.
func (sruo *StepRunUpdateOne) SetAccount(a *Account) *StepRunUpdateOne {
	return sruo.SetAccountID(a.ID)
}

// SetNodeID sets the "node" edge to the Node entity by ID.
func (sruo *StepRunUpdateOne) SetNodeID(id int) *StepRunUpdateOne {
	sruo.mutation.SetNodeID(id)
	return sruo
}

// SetNillableNodeID sets the "node" edge to the Node entity by ID if the given value is not nil.
func (sruo *StepRunUpdateOne) SetNillableNodeID(id *int) *StepRunUpdateOne {
	if id != nil {
		sruo = sruo.SetNodeID(*id)
	}
	return sruo
}

// SetNode sets the "node" edge to the Node entity.
func (sruo *StepRunUpdateOne) SetNode(n *Node) *StepRunUpdateOne {
	return sruo.SetNodeID(n.ID)
}

// Mutation returns the StepRunMutation object of the builder.
func (sruo *StepRunUpdateOne) Mutation() *StepRunMutation {
	return sruo.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (sruo *StepRunUpdateOne) ClearAccount() *StepRunUpdateOne {
	sruo.mutation.ClearAccount()
	return sruo
}

// ClearNode clears the "node" edge to the Node entity.
func (sruo *StepRunUpdateOne) ClearNode() *StepRunUpdateOne {
	sruo.mutation.ClearNode()
	return sruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (sruo *StepRunUpdateOne) Select(field string, fields ...string) *StepRunUpdateOne {
	sruo.fields = append([]string{field}, fields...)
	return sruo
}

// Save executes the query and returns the updated StepRun entity.
func (sruo *StepRunUpdateOne) Save(ctx context.Context) (*StepRun, error) {
	var (
		err  error
		node *StepRun
	)
	if len(sruo.hooks) == 0 {
		if err = sruo.check(); err != nil {
			return nil, err
		}
		node, err = sruo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*StepRunMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = sruo.check(); err != nil {
				return nil, err
			}
			sruo.mutation = mutation
			node, err = sruo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(sruo.hooks) - 1; i >= 0; i-- {
			if sruo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = sruo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sruo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (sruo *StepRunUpdateOne) SaveX(ctx context.Context) *StepRun {
	node, err := sruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (sruo *StepRunUpdateOne) Exec(ctx context.Context) error {
	_, err := sruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sruo *StepRunUpdateOne) ExecX(ctx context.Context) {
	if err := sruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sruo *StepRunUpdateOne) check() error {
	if v, ok := sruo.mutation.Status(); ok {
		if err := steprun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "StepRun.status": %w`, err)}
		}
	}
	return nil
}

func (sruo *StepRunUpdateOne) sqlSave(ctx context.Context) (_node *StepRun, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   steprun.Table,
			Columns: steprun.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: steprun.FieldID,
			},
		},
	}
	id, ok := sruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "StepRun.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := sruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, steprun.FieldID)
		for _, f := range fields {
			if !steprun.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != steprun.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := sruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := sruo.mutation.Step(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: steprun.FieldStep,
		})
	}
	if value, ok := sruo.mutation.Status(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: steprun.FieldStatus,
		})
	}
	if value, ok := sruo.mutation.Reason(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: steprun.FieldReason,
		})
	}
	if sruo.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   steprun.AccountTable,
			Columns: []string{steprun.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: account.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := sruo.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   steprun.AccountTable,
			Columns: []string{steprun.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: account.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if sruo.mutation.NodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   steprun.NodeTable,
			Columns: []string{steprun.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: node.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := sruo.mutation.NodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   steprun.NodeTable,
			Columns: []string{steprun.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: node.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &StepRun{config: sruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, sruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{steprun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
