// Code generated by entc, DO NOT EDIT.

package ent

import (
	"airdrop-bot/ent/account"
	"airdrop-bot/ent/node"
	"airdrop-bot/ent/predicate"
	"airdrop-bot/ent/steprun"
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StepRunQuery is the builder for querying StepRun entities.
type StepRunQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.StepRun
	// eager-loading edges.
	withAccount *AccountQuery
	withNode    *NodeQuery
	withFKs     bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the StepRunQuery builder.
func (srq *StepRunQuery) Where(ps ...predicate.StepRun) *StepRunQuery {
	srq.predicates = append(srq.predicates, ps...)
	return srq
}

// Limit adds a limit step to the query.
func (srq *StepRunQuery) Limit(limit int) *StepRunQuery {
	srq.limit = &limit
	return srq
}

// Offset adds an offset step to the query.
func (srq *StepRunQuery) Offset(offset int) *StepRunQuery {
	srq.offset = &offset
	return srq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (srq *StepRunQuery) Unique(unique bool) *StepRunQuery {
	srq.unique = &unique
	return srq
}

// Order adds an order step to the query.
func (srq *StepRunQuery) Order(o ...OrderFunc) *StepRunQuery {
	srq.order = append(srq.order, o...)
	return srq
}

// QueryAccount chains the current query on the "account" edge.
func (srq *StepRunQuery) QueryAccount() *AccountQuery {
	query := &AccountQuery{config: srq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := srq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := srq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(steprun.Table, steprun.FieldID, selector),
			sqlgraph.To(account.Table, account.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, steprun.AccountTable, steprun.AccountColumn),
		)
		fromU = sqlgraph.SetNeighbors(srq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryNode chains the current query on the "node" edge.
func (srq *StepRunQuery) QueryNode() *NodeQuery {
	query := &NodeQuery{config: srq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := srq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := srq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(steprun.Table, steprun.FieldID, selector),
			sqlgraph.To(node.Table, node.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, steprun.NodeTable, steprun.NodeColumn),
		)
		fromU = sqlgraph.SetNeighbors(srq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first StepRun entity from the query.
// Returns a *NotFoundError when no StepRun was found.
func (srq *StepRunQuery) First(ctx context.Context) (*StepRun, error) {
	nodes, err := srq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{steprun.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (srq *StepRunQuery) FirstX(ctx context.Context) *StepRun {
	node, err := srq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first StepRun ID from the query.
// Returns a *NotFoundError when no StepRun ID was found.
func (srq *StepRunQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = srq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{steprun.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (srq *StepRunQuery) FirstIDX(ctx context.Context) int {
	id, err := srq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single StepRun entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one StepRun entity is found.
// Returns a *NotFoundError when no StepRun entities are found.
func (srq *StepRunQuery) Only(ctx context.Context) (*StepRun, error) {
	nodes, err := srq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{steprun.Label}
	default:
		return nil, &NotSingularError{steprun.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (srq *StepRunQuery) OnlyX(ctx context.Context) *StepRun {
	node, err := srq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only StepRun ID in the query.
// Returns a *NotSingularError when more than one StepRun ID is found.
// Returns a *NotFoundError when no entities are found.
func (srq *StepRunQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = srq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{steprun.Label}
	default:
		err = &NotSingularError{steprun.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (srq *StepRunQuery) OnlyIDX(ctx context.Context) int {
	id, err := srq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of StepRuns.
func (srq *StepRunQuery) All(ctx context.Context) ([]*StepRun, error) {
	if err := srq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return srq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (srq *StepRunQuery) AllX(ctx context.Context) []*StepRun {
	nodes, err := srq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of StepRun IDs.
func (srq *StepRunQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := srq.Select(steprun.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (srq *StepRunQuery) IDsX(ctx context.Context) []int {
	ids, err := srq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (srq *StepRunQuery) Count(ctx context.Context) (int, error) {
	if err := srq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return srq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (srq *StepRunQuery) CountX(ctx context.Context) int {
	count, err := srq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (srq *StepRunQuery) Exist(ctx context.Context) (bool, error) {
	if err := srq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return srq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (srq *StepRunQuery) ExistX(ctx context.Context) bool {
	exist, err := srq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the StepRunQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (srq *StepRunQuery) Clone() *StepRunQuery {
	if srq == nil {
		return nil
	}
	return &StepRunQuery{
		config:      srq.config,
		limit:       srq.limit,
		offset:      srq.offset,
		order:       append([]OrderFunc{}, srq.order...),
		predicates:  append([]predicate.StepRun{}, srq.predicates...),
		withAccount: srq.withAccount.Clone(),
		withNode:    srq.withNode.Clone(),
		// clone intermediate query.
		sql:    srq.sql.Clone(),
		path:   srq.path,
		unique: srq.unique,
	}
}

// WithAccount tells the query-builder to eager-load the nodes that are connected to
// the "account" edge. The optional arguments are used to configure the query builder of the edge.
func (srq *StepRunQuery) WithAccount(opts ...func(*AccountQuery)) *StepRunQuery {
	query := &AccountQuery{config: srq.config}
	for _, opt := range opts {
		opt(query)
	}
	srq.withAccount = query
	return srq
}

// WithNode tells the query-builder to eager-load the nodes that are connected to
// the "node" edge. The optional arguments are used to configure the query builder of the edge.
func (srq *StepRunQuery) WithNode(opts ...func(*NodeQuery)) *StepRunQuery {
	query := &NodeQuery{config: srq.config}
	for _, opt := range opts {
		opt(query)
	}
	srq.withNode = query
	return srq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Step string `json:"step,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.StepRun.Query().
//		GroupBy(steprun.FieldStep).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (srq *StepRunQuery) GroupBy(field string, fields ...string) *StepRunGroupBy {
	group := &StepRunGroupBy{config: srq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := srq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return srq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Step string `json:"step,omitempty"`
//	}
//
//	client.StepRun.Query().
//		Select(steprun.FieldStep).
//		Scan(ctx, &v)
//
func (srq *StepRunQuery) Select(fields ...string) *StepRunSelect {
	srq.fields = append(srq.fields, fields...)
	return &StepRunSelect{StepRunQuery: srq}
}

func (srq *StepRunQuery) prepareQuery(ctx context.Context) error {
	for _, f := range srq.fields {
		if !steprun.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if srq.path != nil {
		prev, err := srq.path(ctx)
		if err != nil {
			return err
		}
		srq.sql = prev
	}
	return nil
}

func (srq *StepRunQuery) sqlAll(ctx context.Context) ([]*StepRun, error) {
	var (
		nodes       = []*StepRun{}
		withFKs     = srq.withFKs
		_spec       = srq.querySpec()
		loadedTypes = [2]bool{
			srq.withAccount != nil,
			srq.withNode != nil,
		}
	)
	if srq.withAccount != nil || srq.withNode != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, steprun.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &StepRun{config: srq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, srq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := srq.withAccount; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*StepRun)
		for i := range nodes {
			if nodes[i].account_step_runs == nil {
				continue
			}
			fk := *nodes[i].account_step_runs
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(account.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "account_step_runs" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Account = n
			}
		}
	}

	if query := srq.withNode; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*StepRun)
		for i := range nodes {
			if nodes[i].node_step_runs == nil {
				continue
			}
			fk := *nodes[i].node_step_runs
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(node.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "node_step_runs" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Node = n
			}
		}
	}

	return nodes, nil
}

func (srq *StepRunQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := srq.querySpec()
	_spec.Node.Columns = srq.fields
	if len(srq.fields) > 0 {
		_spec.Unique = srq.unique != nil && *srq.unique
	}
	return sqlgraph.CountNodes(ctx, srq.driver, _spec)
}

func (srq *StepRunQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := srq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (srq *StepRunQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   steprun.Table,
			Columns: steprun.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: steprun.FieldID,
			},
		},
		From:   srq.sql,
		Unique: true,
	}
	if unique := srq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := srq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, steprun.FieldID)
		for i := range fields {
			if fields[i] != steprun.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := srq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := srq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := srq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := srq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (srq *StepRunQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(srq.driver.Dialect())
	t1 := builder.Table(steprun.Table)
	columns := srq.fields
	if len(columns) == 0 {
		columns = steprun.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if srq.sql != nil {
		selector = srq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if srq.unique != nil && *srq.unique {
		selector.Distinct()
	}
	for _, p := range srq.predicates {
		p(selector)
	}
	for _, p := range srq.order {
		p(selector)
	}
	if offset := srq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := srq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// StepRunGroupBy is the group-by builder for StepRun entities.
type StepRunGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (srgb *StepRunGroupBy) Aggregate(fns ...AggregateFunc) *StepRunGroupBy {
	srgb.fns = append(srgb.fns, fns...)
	return srgb
}

// Scan applies the group-by query and scans the result into the given value.
func (srgb *StepRunGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := srgb.path(ctx)
	if err != nil {
		return err
	}
	srgb.sql = query
	return srgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (srgb *StepRunGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := srgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (srgb *StepRunGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(srgb.fields) > 1 {
		return nil, errors.New("ent: StepRunGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := srgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (srgb *StepRunGroupBy) StringsX(ctx context.Context) []string {
	v, err := srgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (srgb *StepRunGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = srgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{steprun.Label}
	default:
		err = fmt.Errorf("ent: StepRunGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (srgb *StepRunGroupBy) StringX(ctx context.Context) string {
	v, err := srgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (srgb *StepRunGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(srgb.fields) > 1 {
		return nil, errors.New("ent: StepRunGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := srgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (srgb *StepRunGroupBy) IntsX(ctx context.Context) []int {
	v, err := srgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (srgb *StepRunGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = srgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{steprun.Label}
	default:
		err = fmt.Errorf("ent: StepRunGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (srgb *StepRunGroupBy) IntX(ctx context.Context) int {
	v, err := srgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (srgb *StepRunGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(srgb.fields) > 1 {
		return nil, errors.New("ent: StepRunGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := srgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (srgb *StepRunGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := srgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (srgb *StepRunGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = srgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{steprun.Label}
	default:
		err = fmt.Errorf("ent: StepRunGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (srgb *StepRunGroupBy) Float64X(ctx context.Context) float64 {
	v, err := srgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (srgb *StepRunGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(srgb.fields) > 1 {
		return nil, errors.New("ent: StepRunGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := srgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (srgb *StepRunGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := srgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (srgb *StepRunGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = srgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{steprun.Label}
	default:
		err = fmt.Errorf("ent: StepRunGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (srgb *StepRunGroupBy) BoolX(ctx context.Context) bool {
	v, err := srgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (srgb *StepRunGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range srgb.fields {
		if !steprun.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := srgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := srgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (srgb *StepRunGroupBy) sqlQuery() *sql.Selector {
	selector := srgb.sql.Select()
	aggregation := make([]string, 0, len(srgb.fns))
	for _, fn := range srgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(srgb.fields)+len(srgb.fns))
		for _, f := range srgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(srgb.fields...)...)
}

// StepRunSelect is the builder for selecting fields of StepRun entities.
type StepRunSelect struct {
	*StepRunQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (srs *StepRunSelect) Scan(ctx context.Context, v interface{}) error {
	if err := srs.prepareQuery(ctx); err != nil {
		return err
	}
	srs.sql = srs.StepRunQuery.sqlQuery(ctx)
	return srs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (srs *StepRunSelect) ScanX(ctx context.Context, v interface{}) {
	if err := srs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (srs *StepRunSelect) Strings(ctx context.Context) ([]string, error) {
	if len(srs.fields) > 1 {
		return nil, errors.New("ent: StepRunSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := srs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (srs *StepRunSelect) StringsX(ctx context.Context) []string {
	v, err := srs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (srs *StepRunSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = srs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{steprun.Label}
	default:
		err = fmt.Errorf("ent: StepRunSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (srs *StepRunSelect) StringX(ctx context.Context) string {
	v, err := srs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (srs *StepRunSelect) Ints(ctx context.Context) ([]int, error) {
	if len(srs.fields) > 1 {
		return nil, errors.New("ent: StepRunSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := srs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (srs *StepRunSelect) IntsX(ctx context.Context) []int {
	v, err := srs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (srs *StepRunSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = srs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{steprun.Label}
	default:
		err = fmt.Errorf("ent: StepRunSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (srs *StepRunSelect) IntX(ctx context.Context) int {
	v, err := srs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (srs *StepRunSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(srs.fields) > 1 {
		return nil, errors.New("ent: StepRunSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := srs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (srs *StepRunSelect) Float64sX(ctx context.Context) []float64 {
	v, err := srs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (srs *StepRunSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = srs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{steprun.Label}
	default:
		err = fmt.Errorf("ent: StepRunSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (srs *StepRunSelect) Float64X(ctx context.Context) float64 {
	v, err := srs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (srs *StepRunSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(srs.fields) > 1 {
		return nil, errors.New("ent: StepRunSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := srs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (srs *StepRunSelect) BoolsX(ctx context.Context) []bool {
	v, err := srs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (srs *StepRunSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = srs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{steprun.Label}
	default:
		err = fmt.Errorf("ent: StepRunSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (srs *StepRunSelect) BoolX(ctx context.Context) bool {
	v, err := srs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (srs *StepRunSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := srs.sql.Query()
	if err := srs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
