// Code generated by ent, DO NOT EDIT.

package ent

import (
	"airdrop-bot/ent/predicate"
	"airdrop-bot/ent/steprun"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StepRunDelete is the builder for deleting a StepRun entity.
type StepRunDelete struct {
	config
	hooks    []Hook
	mutation *StepRunMutation
}

// Where appends a list predicates to the StepRunDelete builder.
func (srd *StepRunDelete) Where(ps ...predicate.StepRun) *StepRunDelete {
	srd.mutation.Where(ps...)
	return srd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (srd *StepRunDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, StepRunMutation](ctx, srd.sqlExec, srd.mutation, srd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (srd *StepRunDelete) ExecX(ctx context.Context) int {
	n, err := srd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (srd *StepRunDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(steprun.Table, sqlgraph.NewFieldSpec(steprun.FieldID, field.TypeInt))
	if ps := srd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, srd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	srd.mutation.done = true
	return affected, err
}

// StepRunDeleteOne is the builder for deleting a single StepRun entity.
type StepRunDeleteOne struct {
	srd *StepRunDelete
}

// Where appends a list predicates to the StepRunDelete builder.
func (srdo *StepRunDeleteOne) Where(ps ...predicate.StepRun) *StepRunDeleteOne {
	srdo.srd.mutation.Where(ps...)
	return srdo
}

// Exec executes the deletion query.
func (srdo *StepRunDeleteOne) Exec(ctx context.Context) error {
	n, err := srdo.srd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{steprun.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (srdo *StepRunDeleteOne) ExecX(ctx context.Context) {
	if err := srdo.Exec(ctx); err != nil {
		panic(err)
	}
}
