name: build

on:
  pull_request:
    branches: [ main ]
    
jobs:
  go_build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.0'

      - name: Build
        run: go build -v ./...
