// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// Node is the predicate function for node builders.
type Node func(*sql.Selector)

// StepRun is the predicate function for steprun builders.
type StepRun func(*sql.Selector)
